package util

import "go.mongodb.org/mongo-driver/mongo"

// Variable block
var Client *mongo.Client
var CollectionName = [4]string{"users", "merchants", "outlets", "transactions"}

// Constanta block
const DatabaseName string = "majoo"
const Port string = "8080"

// Error block
const Error0 = "Error 0. Please re-check your request"             // middleware-create.go
const Error1 = "Error 1. Authorization token error"                // middleware-create.go
const Error2 = "Error 2. Authorization token error"                // middleware-create.go
const Error3 = "Error 3. Authorization token error"                // middleware-create.go
const Error4 = "Error 4. merchant_name request parameter is empty" // middleware-create.go
const Error5 = "Error 5. user_id parameter not found"              // middleware-create.go
const Error6 = "Error 6. Server program error"                     // middleware-create.go
const Error7 = "Error 7. merchant_name is exist"                   // middleware-create.go
const Error8 = "Error 8. Server program error"                     // middleware-create.go
const Error9 = "Error 9. Server program error"                     // middleware-create.go
const Error10 = "Error 10. Please re-check your request"           // middleware-create.go
const Error11 = "Error 11. Authorization token error"              // middleware-create.go
const Error12 = "Error 12. Authorization token error"              // middleware-create.go
const Error13 = "Error 13. Authorization token error"              // middleware-create.go
const Error14 = "Error 14. outlet_name request parameter is empty" // middleware-create.go
const Error15 = "Error 15. user_id parameter not found"            // middleware-create.go
const Error16 = "Error 16. Server program error"                   // middleware-create.go
const Error17 = "Error 17. merchant_id parameter not found"        // middleware-create.go
const Error18 = "Error 18. Server program error"                   // middleware-create.go
const Error19 = "Error 19. outlet_name is exist"                   // middleware-create.go
const Error20 = "Error 20. Server program error"                   // middleware-create.go
const Error21 = "Error 21. Server program error"                   // middleware-create.go
const Error22 = "Error 22. Please re-check your request"           // middleware-create.go
const Error23 = "Error 23. Authorization token error"              // middleware-create.go
const Error24 = "Error 24. Authorization token error"              // middleware-create.go
const Error25 = "Error 25. Authorization token error"              // middleware-create.go
const Error26 = "Error 26. bill_total request parameter is 0"      // middleware-create.go
const Error27 = "Error 27. user_id parameter not found"            // middleware-create.go
const Error28 = "Error 28. Server program error"                   // middleware-create.go
const Error29 = "Error 29. merchant_id parameter not found"        // middleware-create.go
const Error30 = "Error 30. Server program error"                   // middleware-create.go
const Error31 = "Error 31. outlet_id parameter not found"          // middleware-create.go
const Error32 = "Error 32. Server program error"                   // middleware-create.go
const Error33 = "Error 33. Server program error"                   // middleware-create.go
const Error34 = "Error 34. Server program error"                   // middleware-create.go
const Error35 = "Error 35. Authorization token error"              // middleware-delete.go
const Error36 = "Error 36. Authorization token error"              // middleware-delete.go
const Error37 = "Error 37. Authorization token error"              // middleware-delete.go
const Error38 = "Error 38. Server program error"                   // middleware-delete.go
const Error39 = "Error 39. No data deleted"                        // middleware-delete.go
const Error40 = "Error 40. Server program error"                   // middleware-delete.go
const Error41 = "Error 41. Please re-check your request"           // middleware-delete.go
const Error42 = "Error 42. Authorization token error"              // middleware-delete.go
const Error43 = "Error 43. Authorization token error"              // middleware-delete.go
const Error44 = "Error 44. Authorization token error"              // middleware-delete.go
const Error45 = "Error 45. Server program error"                   // middleware-delete.go
const Error46 = "Error 46. No data deleted"                        // middleware-delete.go
const Error47 = "Error 47. Server program error"                   // middleware-delete.go
const Error48 = "Error 48. Please re-check your request"           // middleware-delete.go
const Error49 = "Error 49. Authorization token error"              // middleware-delete.go
const Error50 = "Error 50. Authorization token error"              // middleware-delete.go
const Error51 = "Error 51. Authorization token error"              // middleware-delete.go
const Error52 = "Error 52. Server program error"                   // middleware-delete.go
const Error53 = "Error 53. No data deleted"                        // middleware-delete.go
const Error54 = "Error 54. Server program error"                   // middleware-delete.go
const Error55 = "Error 55. Please re-check your request"           // middleware-delete.go
const Error56 = "Error 56. Authorization token error"              // middleware-delete.go
const Error57 = "Error 57. Authorization token error"              // middleware-delete.go
const Error58 = "Error 58. Authorization token error"              // middleware-delete.go
const Error59 = "Error 59. Server program error"                   // middleware-delete.go
const Error60 = "Error 60. No data deleted"                        // middleware-delete.go
const Error61 = "Error 61. Server program error"                   // middleware-delete.go
const Error62 = "Error 62. Please re-check your request"           // middleware-other.go
const Error63 = "Error 63. user_name request parameter is empty"   // middleware-other.go
const Error64 = "Error 64. user_name is exist"                     // middleware-other.go
const Error65 = "Error 65. Server program error"                   // middleware-other.go
const Error66 = "Error 66. Server program error"                   // middleware-other.go
const Error67 = "Error 67. Please re-check your request"           // middleware-other.go
const Error68 = "Error 68. Your login data not found"              // middleware-other.go
const Error69 = "Error 69. Server program error"                   // middleware-other.go
const Error70 = "Error 70. Server program error"                   // middleware-other.go
const Error71 = "Error 71. Server program error"                   // middleware-other.go
const Error72 = "Error 72. Server program error"                   // middleware-other.go
const Error73 = "Error 73. Server program error"                   // middleware-other.go
const Error74 = "Error 74. Server program error"                   // middleware-other.go
const Error75 = "Error 75. Server program error"                   // middleware-other.go
const Error76 = "Error 76. Server program error"                   // middleware-other.go
const Error77 = "Error 77. Authorization token error"              // middleware-read.go
const Error78 = "Error 78. Authorization token error"              // middleware-read.go
const Error79 = "Error 79. Authorization token error"              // middleware-read.go
const Error80 = "Error 80. user_id parameter not found"            // middleware-read.go
const Error81 = "Error 81. Server program error"                   // middleware-read.go
const Error82 = "Error 82. Server program error"                   // middleware-read.go
const Error83 = "Error 83. Authorization token error"              // middleware-read.go
const Error84 = "Error 84. Authorization token error"              // middleware-read.go
const Error85 = "Error 85. Authorization token error"              // middleware-read.go
const Error86 = "Error 86. user_id parameter not found"            // middleware-read.go
const Error87 = "Error 87. Server program error"                   // middleware-read.go
const Error88 = "Error 88. Server program error"                   // middleware-read.go
const Error89 = "Error 89. merchant_id parameter not found"        // middleware-read.go
const Error90 = "Error 90. Authorization token error"              // middleware-read.go
const Error91 = "Error 91. Authorization token error"              // middleware-read.go
const Error92 = "Error 92. Authorization token error"              // middleware-read.go
const Error93 = "Error 93. Server program error"                   // middleware-read.go
const Error94 = "Error 94. Server program error"                   // middleware-read.go
const Error95 = "Error 95. Server program error"                   // middleware-read.go
const Error96 = "Error 96. Server program error"                   // middleware-read.go
const Error97 = "Error 97. Please re-check your request"           // middleware-read.go
const Error98 = "Error 98. Please re-check your request"           // middleware-read.go
const Error99 = "Error 99. Authorization token error"              // middleware-read.go
const Error100 = "Error 100. Authorization token error"            // middleware-read.go
const Error101 = "Error 101. Authorization token error"            // middleware-read.go
const Error102 = "Error 102. Server program error"                 // middleware-read.go
const Error103 = "Error 103. Server program error"                 // middleware-read.go
const Error104 = "Error 104. Server program error"                 // middleware-read.go
const Error105 = "Error 105. Server program error"                 // middleware-read.go
const Error106 = "Error 106. Server program error"                 // middleware-read.go
const Error107 = "Error 107. Authorization token error"            // middleware-read.go
const Error108 = "Error 108. Authorization token error"            // middleware-read.go
const Error109 = "Error 109. limit parameter is empty"             // middleware-read.go
const Error110 = "Error 110. Server program error"                 // middleware-read.go
const Error111 = "Error 111. Server program error"                 // middleware-read.go
const Error112 = "Error 112. Authorization token error"            // middleware-read.go
const Error113 = "Error 113. Server program error"                 // middleware-read.go
const Error114 = "Error 114. Server program error"                 // middleware-read.go
const Error115 = "Error 115. Server program error"                 // middleware-read.go
const Error116 = "Error 116. Server program error"                 // middleware-read.go
const Error117 = "Error 117. Server program error"                 // middleware-read.go
const Error118 = "Error 118. Authorization token error"            // middleware-read.go
const Error119 = "Error 119. Authorization token error"            // middleware-read.go
const Error120 = "Error 120. limit parameter is empty"             // middleware-read.go
const Error121 = "Error 121. Server program error"                 // middleware-read.go
const Error122 = "Error 122. Server program error"                 // middleware-read.go
const Error123 = "Error 123. Authorization token error"            // middleware-read.go
const Error124 = "Error 124. Server program error"                 // middleware-read.go
const Error125 = "Error 125. Server program error"                 // middleware-read.go
const Error126 = "Error 126. Server program error"                 // middleware-read.go
const Error127 = "Error 127. Server program error"                 // middleware-read.go
const Error128 = "Error 128. Server program error"                 // middleware-read.go
const Error129 = "Error 129. Please re-check your request"         // middleware-update.go
const Error130 = "Error 130. Authorization token error"            // middleware-update.go
const Error131 = "Error 131. Authorization token error"            // middleware-update.go
const Error132 = "Error 132. Authorization token error"            // middleware-update.go
const Error133 = "Error 133. Server program error"                 // middleware-update.go
const Error134 = "Error 134. Server program error"                 // middleware-update.go
const Error135 = "Error 135. No data updated"                      // middleware-update.go
const Error136 = "Error 136. Server program error"                 // middleware-update.go
const Error137 = "Error 137. Please re-check your request"         // middleware-update.go
const Error138 = "Error 138. Authorization token error"            // middleware-update.go
const Error139 = "Error 139. Authorization token error"            // middleware-update.go
const Error140 = "Error 140. Authorization token error"            // middleware-update.go
const Error141 = "Error 141. Server program error"                 // middleware-update.go
const Error142 = "Error 142. Server program error"                 // middleware-update.go
const Error143 = "Error 143. Server program error"                 // middleware-update.go
const Error144 = "Error 144. Server program error"                 // middleware-update.go
const Error145 = "Error 145. Please re-check your request"         // middleware-update.go
const Error146 = "Error 146. Authorization token error"            // middleware-update.go
const Error147 = "Error 147. Authorization token error"            // middleware-update.go
const Error148 = "Error 148. Authorization token error"            // middleware-update.go
const Error149 = "Error 149. Server program error"                 // middleware-update.go
const Error150 = "Error 150. Server program error"                 // middleware-update.go
const Error151 = "Error 151. No data updated"                      // middleware-update.go
const Error152 = "Error 152. Server program error"                 // middleware-update.go
const Error153 = "Error 153. Please re-check your request"         // middleware-update.go
const Error154 = "Error 154. Authorization token error"            // middleware-update.go
const Error155 = "Error 155. Authorization token error"            // middleware-update.go
const Error156 = "Error 156. Authorization token error"            // middleware-update.go
const Error157 = "Error 157. Server program error"                 // middleware-update.go
const Error158 = "Error 158. Server program error"                 // middleware-update.go
const Error159 = "Error 159. Server program error"                 // middleware-update.go
const Error160 = "Error 160. Server program error"                 // middleware-update.go
