version: "3.8"

volumes:
    mongo:
        name: mongo

services:
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - 27017:27017
        networks:
            - majoo
        volumes:
            - type: volume
              source: mongo
              target: /data/db
    majoo-server:
        container_name: majoo-server
        image: fikriprayoga1/majoo-server:1.0
        ports:
            - 8080:8080
        networks:
            - majoo
        depends_on:
            - mongo
        environment:
            - MONGO_HOST=mongo        

networks:
    majoo:
        name: majoo